version: "3.8"

services:

  mongodb:
    image: mongo
    restart: "on-failure"
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_DB_CONNECTION_STRING=$MONGO_DOCKER_URI # optional for debugging via mongosh

  mongoexpress:
    image: mongo-express
    restart: "on-failure"
    ports:
      - $DB_UI_LOCAL_PORT:$DB_UI_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=$DB_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$DB_PASSWORD

  opencats:
    build:
      context: ../opencats
    ports:
      - 8090:80
    links:
      - mysql

  mysql:
      image: mysql:5.5
      ports:
        - 3307:3306
      volumes:
        - opencats_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cats_dev
        MYSQL_USER: cats
        MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql:db
    environment:
      PMA_HOST: db
      PMA_USER: cats
      PMA_PASSWORD: password

volumes:
  mongodb_data: {}
  opencats_data: {}